### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by SqrTT** [tgandrews/atom-easy-jsdoc#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [atom-easy-jsdoc](https://github.com/tgandrews/atom-easy-jsdoc) package, v4.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /home/sqrtt/.atom/packages/atom-easy-jsdoc/lib/regex/jsdoc.js:35

TypeError: Cannot read property 'match' of undefined
    at continueComments (/home/sqrtt/.atom/packages/atom-easy-jsdoc/lib/regex/jsdoc.js:35:25)
    at Object.module.exports.newline (/home/sqrtt/.atom/packages/atom-easy-jsdoc/lib/regex/jsdoc.js:127:9)
    at atom-text-editor.editorNewline (/home/sqrtt/.atom/packages/atom-easy-jsdoc/lib/index.js:61:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:52.7.0 bart:openConfig (atom-pane.pane.active)
     -2:48.5.0 docblockr:parse-enter (atom-text-editor#bart-watchlist.editor.bart-watchlist.is-focused)
     -1:29.2.0 core:paste (atom-text-editor.editor.is-focused)
 22x -1:25.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -1:20.2.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:14.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:12.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:11.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:11.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:10.4.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -1:09.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:20.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:20.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.7.0 bart:openConfig (atom-text-editor.editor.is-focused)
     -0:13.3.0 docblockr:parse-enter (atom-text-editor#bart-watchlist.editor.bart-watchlist.is-focused)
     -0:13.3.0 editor:newline (atom-text-editor#bart-watchlist.editor.bart-watchlist.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-on-github",
      "ascii-art",
      "vim-mode",
      "atom-typescript",
      "linter",
      "jshint",
      "linter-flow",
      "ide-flow",
      "linter-flow-plus",
      "git-control",
      "activate-power-mode",
      "turbo-javascript",
      "node-debugger",
      "atom-jasmine"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Bart, v1.1.0
Quick-JavaScript, v0.16.0
atom-easy-jsdoc, v4.5.0
atom-jshint, v2.0.0
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
docblockr, v0.7.3
flow, v0.5.3
language-demandware, v0.1.0
language-javascript-semantic, v0.2.1
linter-eslint, v7.2.2
linter-jscs, v4.0.0
minimap, v4.23.5
minimap-cursorline, v0.1.0
pigments, v0.26.2

# Dev
No dev packages
```

**Comment by tgandrews** [comment]
Thanks for the report. I will investigate.

**Comment by SqrTT** [comment]
this happen when current editor contain new/empty file, and `newline` event is triggered from mini-editor  (in my case opened in modal window)

**Comment by tgandrews** [comment]
That's great. I'll give it a try.
