### ISSUE TITLE
Error in Typescript file when "Right Click" > "Add a JSDoc comment"

### ISSUE THREAD

**Issue by jhm-ciberman** [tgandrews/atom-easy-jsdoc#34]
Bug report generated by ATOM:

[Enter steps to reproduce below:]

1. Open a typescript file like this:
```
    getRect(target?):Rectangle{
        if (target) {
            return new Rectangle(this.xx - target.xx, this.yy - target.yy, this.width, this.height);
        }
        return new Rectangle(this.x, this.y, this.width, this.height);
    }
```

2. Right Click > Add a JSDoc comment
3. Atom will show this error:

**Atom Version**: 1.9.6
**System**: Windows 10
**Thrown From**: [atom-easy-jsdoc](https://github.com/tgandrews/atom-easy-jsdoc) package, v4.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token (14:11)

```
At C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\location.js:25

SyntaxError: Unexpected token (14:11)
    at Parser.pp.raise (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.unexpected (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\util.js:89:8)
    at Parser.pp.expect (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\util.js:83:33)
    at Parser.pp.parseMethod (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\expression.js:893:8)
    at Parser.pp.parseClassMethod (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:827:8)
    at Parser.pp.parseClassBody (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:788:10)
    at Parser.pp.parseClass (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:666:8)
    at Parser.pp.parseExport (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:886:19)
    at Parser.pp.parseStatement (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:141:81)
    at Parser.pp.parseBlockBody (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:529:21)
    at Parser.pp.parseTopLevel (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\statement.js:36:8)
    at Parser.parse (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\parser\index.js:129:19)
    at Object.parse (C:\Users\xxxxxxxxxxx\.atom\packages\atom-easy-jsdoc\node_modules\babylon\lib\index.js:47:47)
    at getAST (C:/Users/xxxxxxxxxxx/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:25:22)
    at parse (C:/Users/xxxxxxxxxxx/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:242:15)
    at comment (C:/Users/xxxxxxxxxxx/.atom/packages/atom-easy-jsdoc/lib/jsdocer.js:17:16)
    at createComment (C:/Users/xxxxxxxxxxx/.atom/packages/atom-easy-jsdoc/lib/index.js:23:29)
    at atom-text-editor.jsdocBlock (C:/Users/xxxxxxxxxxx/.atom/packages/atom-easy-jsdoc/lib/index.js:54:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\xxxxxxxxxxx\AppData\Local\atom\app-1.9.6\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\xxxxxxxxxxx\AppData\Local\atom\app-1.9.6\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\xxxxxxxxxxx\AppData\Local\atom\app-1.9.6\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\xxxxxxxxxxx\AppData\Local\atom\app-1.9.6\resources\app.asar\src\atom-environment.js:1110:28)
    at EventEmitter.outerCallback (C:\Users\xxxxxxxxxxx\AppData\Local\atom\app-1.9.6\resources\app.asar\src\application-delegate.js:340:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

### Commands

```
     -2:19.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:19.4.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -1:50.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48 core:save (atom-text-editor.editor.is-focused)
  5x -1:47.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -1:23.7.0 grammar-selector:show (atom-text-editor.editor)
     -1:08.5.0 linter:lint (atom-text-editor.editor)
     -0:57.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.2.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:51.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:49.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:49.8.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -0:47.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.6.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:43.5.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:05.8.0 jsdoc:block (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsdoc-generator"
    ],
    "packagesWithKeymapsDisabled": [
      "docs-snippets"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai-complete-syntax"
    ]
  },
  "atom-easy-jsdoc": {
    "beta": true,
    "useReturns": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.3 (active)
ansi-to-utf8, v0.4.0 (inactive)
api-docs, v0.0.6 (active)
atom-easy-jsdoc, v4.6.0 (active)
atom-typescript, v10.1.6 (active)
autoclose-html, v0.23.0 (active)
br4ckets-dark, v1.0.0 (inactive)
docs-snippets, v0.8.0 (active)
duplicate-line-or-selection, v0.5.0 (inactive)
jsdoc-preview, v1.1.0 (active)
keyboard-localization, v1.4.18 (active)
language-blade, v0.25.3 (active)
laravel-5-snippets, v0.8.0 (active)
linter, v1.11.16 (active)
min-ui, v0.0.1 (inactive)
monokai-complete-syntax, v0.2.3 (active)
monokai-dark, v1.3.0 (inactive)
monokai-shade-src, v0.3.4 (inactive)
v-bootstrap4, v0.1.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by tgandrews** [comment]
Unfortunately, Typescript is a superset and hence not valid JavaScript. JSDoc requires valid JavaScript at the moment.
