### ISSUE TITLE
Unexpected token when inserting a JSDoc comment

### ISSUE THREAD

**Issue by dbstiles** [tgandrews/atom-easy-jsdoc#35]
Error occurs when inserting a JSDoc comment for a method by either Ctrl+Shift+D or the option from the menu.

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-easy-jsdoc](https://github.com/tgandrews/atom-easy-jsdoc) package, v4.6.0

### Stack Trace

Uncaught SyntaxError: Unexpected token (13:7)

```
At ~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/location.js:25

SyntaxError: Unexpected token (13:7)
    at Parser.pp.raise (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.expect (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.parseExportSpecifiers (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:969:8)
    at Parser.pp.parseExport (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:902:28)
    at Parser.pp.parseStatement (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:141:81)
    at Parser.pp.parseBlockBody (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/index.js:129:19)
    at Object.parse (~/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/index.js:47:47)
    at getAST (~/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:25:22)
    at parse (~/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:242:15)
    at comment (~/.atom/packages/atom-easy-jsdoc/lib/jsdocer.js:17:16)
    at createComment (~/.atom/packages/atom-easy-jsdoc/lib/index.js:23:29)
    at atom-text-editor.jsdocBlock (~/.atom/packages/atom-easy-jsdoc/lib/index.js:54:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:10.1.0 application:open (ul.list-inline.tab-bar.inset-panel)
     -0:07.4.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:02.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:01.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:00.0 jsdoc:block (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "atom-easy-jsdoc": {
    "beta": true,
    "useReturns": true
  }
}
```

### Installed Packages

```coffee
# User
angular-2-typeScript-snippets, v0.4.6 (active)
atom-beautify, v0.29.10 (inactive)
atom-easy-jsdoc, v4.6.0 (active)
atom-typescript, v10.1.5 (active)
linter, v1.11.14 (active)
linter-tslint, v0.10.0 (active)
ng2-snippets, v0.2.2 (active)
pp-markdown, v0.0.2 (active)
tool-bar-markdown-writer, v0.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by tgandrews** [comment]
Do you have a small example of the code that causes this error? Currently, we require valid JavaScript to be able to create JSDoc comments.

**Comment by kithokit** [comment]
I have the same problem too. How may i help u?

**Comment by tgandrews** [comment]
Would you be able to provide a code snippet that created this issue. @kithokit

**Comment by kithokit** [comment]
`/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/location.js:25
Hide Stack Trace
SyntaxError: Unexpected token (8:49)
    at Parser.pp.raise (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseAsyncArrowFromCallExpression (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:364:47)
    at Parser.pp.parseSubscripts (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:315:21)
    at Parser.pp.parseExprSubscripts (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:282:15)
    at Parser.pp.parseMaybeUnary (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExprListItem (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:1032:16)
    at Parser.pp.parseCallExpressionArguments (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:348:20)
    at Parser.pp.parseSubscripts (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:311:31)
    at Parser.pp.parseExprSubscripts (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:282:15)
    at Parser.pp.parseMaybeUnary (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExpression (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:92:19)
    at Parser.pp.parseStatement (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:163:19)
    at Parser.pp.parseBlockBody (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/index.js:129:19)
    at Object.parse (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/index.js:47:47)
    at getAST (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:39:20)
    at parse (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:261:13)
    at comment (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/lib/jsdocer.js:26:41)
    at createComment (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/lib/index.js:23:29)
    at atom-text-editor.jsdocBlock (/Users/kit_ho/.atom/packages/atom-easy-jsdoc/lib/index.js:54:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)`

**Comment by tgandrews** [comment]
I mean the JavaScript code you are trying to add a JSDoc comment to. 

The parser is reading the file in the current open editor and finding an invalid token. I assume this is because either:
1. The parser has a bug.
2. The JavaScript is invalid.

**Comment by tgandrews** [comment]
Closing until valid JS code found to cause this issue.
