### ISSUE TITLE
Uncaught SyntaxError: Unexpected token (16:4)

### ISSUE THREAD

**Issue by jalleyne** [tgandrews/atom-easy-jsdoc#36]
[Enter steps to reproduce below:]

1. Create a function definition
2. Press shortcut to create comment block
3. Comment block will be duplicated and syntax error popup
4. Press undo to remove one of the comment blocks

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-easy-jsdoc](https://github.com/tgandrews/atom-easy-jsdoc) package, v4.7.0

### Stack Trace

Uncaught SyntaxError: Unexpected token (16:4)

```
At /Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/location.js:25

SyntaxError: Unexpected token (16:4)
    at Parser.pp.raise (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:522:12)
    at Parser.pp.parseExprSubscripts (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:277:19)
    at Parser.pp.parseMaybeUnary (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:257:19)
    at Parser.pp.parseExprOps (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:188:19)
    at Parser.pp.parseMaybeConditional (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExpression (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/expression.js:92:19)
    at Parser.pp.parseStatement (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:163:19)
    at Parser.pp.parseBlockBody (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/parser/index.js:129:19)
    at Object.parse (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/node_modules/babylon/lib/index.js:47:47)
    at getAST (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:39:20)
    at parse (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:261:13)
    at comment (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/lib/jsdocer.js:26:41)
    at createComment (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/lib/index.js:23:29)
    at atom-text-editor.jsdocBlock (/Users/jovanalleyne/.atom/packages/atom-easy-jsdoc/lib/index.js:54:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:43 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:42.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:44.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -2:44.3.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -2:44 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:43.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:20.8.0 jsdoc:block (atom-text-editor.editor.is-focused)
  5x -1:17.9.0 core:undo (atom-text-editor.editor.is-focused)
     -1:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:15 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:14.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:09.2.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -1:08.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.2.0 jsdoc:block (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "restore-windows",
      "save-session",
      "linter-js-standard-jsx",
      "react",
      "linter-jshint"
    ],
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "monokai-blackboard"
    ]
  },
  "atom-easy-jsdoc": {
    "beta": true
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.3.0 (active)
atom-easy-jsdoc, v4.7.0 (inactive)
atom-material-numix-syntax, v0.2.1 (inactive)
atom-material-syntax, v0.4.6 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.2 (active)
bottom-dock, v0.4.4 (active)
coffee-compile, v0.22.0 (active)
color-picker, v2.2.2 (active)
dockerletion, v0.2.0 (active)
dracula-theme, v1.2.8 (inactive)
file-icons, v1.7.19 (active)
git-log, v0.4.1 (active)
go-quick-import, v0.2.1-rc.0 (active)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.37 (active)
language-babel, v2.37.1 (active)
language-docker, v1.1.7 (active)
language-jade, v0.7.2 (active)
language-javascript-better, v1.7.1 (active)
language-javascript-jsx, v0.3.7 (active)
language-nginx, v0.6.1 (active)
language-terraform, v0.7.4 (active)
linter, v1.11.16 (active)
linter-coffeelint, v1.1.2 (active)
linter-docker, v0.1.2 (active)
linter-eslint, v7.3.1 (active)
linter-js-yaml, v1.2.5 (active)
linter-jshint, v2.1.0 (inactive)
linter-less, v2.6.0 (active)
linter-swagger, v0.3.6 (active)
linter-tidy, v2.2.0 (active)
markdown-scroll-sync, v2.1.2 (active)
maximize-panes, v0.2.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
monokai, v0.18.0 (inactive)
monokai-blackboard, v0.3.0 (active)
monokai-dark, v1.3.0 (inactive)
move-panes, v0.2.0 (inactive)
native-ui, v0.18.3 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.34.0 (active)
pretty-json, v1.6.0 (active)
react, v0.16.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
source-preview, v0.5.0 (inactive)
source-preview-less, v0.1.6 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
swap-panes, v0.2.0 (active)
todo-show, v1.7.0 (inactive)
travis-ci-status, v1.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by tgandrews** [comment]
Thanks for the report. Do you have a sample of the code that produces the
problem?

**Comment by jalleyne** [comment]
I think i narrowed down the problem to having a syntax error in the executing file. Notice the second function doesn't have the function keyword. If i fix that the docs seem to generate now.

```javascript


export function validateSessionToken(token){

}


export decodeSessionToken(token){

}


```

**Comment by tgandrews** [comment]
Currently, we require a valid JS file. You should be presented with a message saying that we require valid JavaScript and it does with the JS you provided for me.

![js error](https://cloud.githubusercontent.com/assets/180903/18544184/636860c2-7b2b-11e6-8157-1035ba4bdc53.PNG)

I wonder if there is a packaging/release bug here. Would you be able to access the code in your .atom/modules/atom-easy-jsdoc folder and make it available as a gist?

**Comment by tgandrews** [comment]
Closing until we have recreation steps.
