### ISSUE TITLE
Uncaught Error: Unknown param type - When using a function as default value

### ISSUE THREAD

**Issue by albertbuchard** [tgandrews/atom-easy-jsdoc#45]
When using a function as default parameter such as here : 
```
class xxx() {
...
loadFile(fileIndex = mandatory()) {}
...
}
```

Returns an error: 
```
Uncaught Error: Unknown param type: CallExpression
/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:172
Hide Stack Trace
Error: Unknown param type: CallExpression
    at parseAssignmentParam (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:172:11)
    at /Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:241:23
    at Array.reduce (native)
    at simplifyParams (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:239:17)
    at simplifyFuncNode (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:292:13)
    at simplifyNode (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:280:6)
    at parse (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:327:22)
    at comment (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/jsdocer.js:17:16)
    at createComment (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/index.js:23:29)
    at atom-text-editor.jsdocBlock (/Users/Pro/.atom/packages/atom-easy-jsdoc/lib/index.js:54:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/ly/rxdtkql964n11rrqxwx3htjm0000gn/T/AppTranslocation/ED742E57-BFD9-4113-A22B-972CC1BA920A/d/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /private/var/folders/ly/rxdtkql964n11rrqxwx3htjm0000gn/T/AppTranslocation/ED742E57-BFD9-4113-A22B-972CC1BA920A/d/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/ly/rxdtkql964n11rrqxwx3htjm0000gn/T/AppTranslocation/ED742E57-BFD9-4113-A22B-972CC1BA920A/d/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/ly/rxdtkql964n11rrqxwx3htjm0000gn/T/AppTranslocation/ED742E57-BFD9-4113-A22B-972CC1BA920A/d/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/ly/rxdtkql964n11rrqxwx3htjm0000gn/T/AppTranslocation/ED742E57-BFD9-4113-A22B-972CC1BA920A/d/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/private/var/folders/ly/rxdtkql964n11rrqxwx3htjm0000gn/T/AppTranslocation/ED742E57-BFD9-4113-A22B-972CC1BA920A/d/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by tgandrews** [comment]
Awesome. Definite bug as this is unsupported. Thanks for the report!
