### ISSUE TITLE
Uncaught Error: Unknown param type: MemberExpression

### ISSUE THREAD

**Issue by phun-ky** [tgandrews/atom-easy-jsdoc#64]
This method is giving me this error:

    export const fullApiUrl = (apiUrl, baseUrl = config.apiUrl) => customerNumber => {
      return typeof customerNumber !== 'undefined'
        ? `${baseUrl}/customers/${customerNumber}${apiUrl}`
        : baseUrl + apiUrl;
    };

It is the default value for `baseUrl that is the culprit here.

1. ctrl + shift + j in a js file with cursor at given function above

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.1
**Thrown From**: [atom-easy-jsdoc](https://github.com/tgandrews/atom-easy-jsdoc) package 4.12.2

### Stack Trace

Uncaught Error: Unknown param type: MemberExpression

```
At /home/alexander/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:193

Error: Unknown param type: MemberExpression
    at parseAssignmentParam (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:193:11)
    at /packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:262:23
    at Array.reduce (native)
    at simplifyParams (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:260:17)
    at simplifyFuncNode (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:316:13)
    at simplifyNode (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:304:6)
    at parse (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:367:22)
    at comment (/packages/atom-easy-jsdoc/lib/jsdocer.js:17:16)
    at createComment (/packages/atom-easy-jsdoc/lib/index.js:24:29)
    at HTMLElement.jsdocBlock (/packages/atom-easy-jsdoc/lib/index.js:58:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:19.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:16.4.0 intentions:highlight (input.hidden-input)
     -0:16.4.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:16 pane:move-active-item-to-top-of-stack (div.panels-item)
     -0:15.3.0 pane:show-next-recently-used-item (div.panels-item)
     -0:15.2.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:15.1.0 intentions:highlight (input.hidden-input)
  2x -0:15.1.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:14.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:13.4.0 intentions:highlight (input.hidden-input)
     -0:13 jsdoc:block (input.hidden-input)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.2 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.11 
hidpi 0.14.0 
intentions 1.1.5 
language-babel 2.73.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.7 
merge-conflicts 1.4.5 
pigments 0.40.2 
project-manager 3.3.5 
Stylus 3.1.1 
svg-preview 0.11.0 
```

**Comment by tgandrews** [comment]
Thanks for the report. I'll aim to resolve it asap
