### ISSUE TITLE
Uncaught Error: Unknown param type: ArrowFunctionExpression

### ISSUE THREAD

**Issue by jhessin** [tgandrews/atom-easy-jsdoc#72]
[Enter steps to reproduce:]

1. Create a class
2. add a constructor that takes as a parameter a fat-arrow function.
3. give said parameter a default value of () => {} (an empty fat arrow function).
4. Try to run with ctrl-shift-j or ctrl-shift-d

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [atom-easy-jsdoc](https://github.com/tgandrews/atom-easy-jsdoc) package 4.12.4

### Stack Trace

Uncaught Error: Unknown param type: ArrowFunctionExpression

```
At /home/jhessin/.atom/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:196

Error: Unknown param type: ArrowFunctionExpression
    at parseAssignmentParam (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:196:11)
    at props.reduce.name (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:248:25)
    at Array.reduce (native)
    at parseDestructuredParam (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:242:6)
    at /packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:265:23
    at Array.reduce (native)
    at simplifyParams (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:263:17)
    at simplifyClassMethodNode (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:334:13)
    at simplifyNode (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:307:6)
    at parse (/packages/atom-easy-jsdoc/lib/jsdoc/funcParser.js:370:22)
    at comment (/packages/atom-easy-jsdoc/lib/jsdocer.js:17:16)
    at createComment (/packages/atom-easy-jsdoc/lib/index.js:24:29)
    at HTMLElement.jsdocBlock (/packages/atom-easy-jsdoc/lib/index.js:58:9)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:47.2.0 core:save (input.hidden-input)
     -0:40 intentions:highlight (input.hidden-input)
  3x -0:38.6.0 core:undo (input.hidden-input)
  6x -0:36.9.0 core:move-left (input.hidden-input)
     -0:35.2.0 core:backspace (input.hidden-input)
     -0:35 editor:newline (input.hidden-input)
     -0:34.4.0 intentions:highlight (input.hidden-input)
  3x -0:34 editor:move-line-up (input.hidden-input)
     -0:32.4.0 intentions:highlight (input.hidden-input)
     -0:32.2.0 core:save (input.hidden-input)
     -0:27.4.0 core:move-left (input.hidden-input)
  3x -0:26.7.0 core:backspace (input.hidden-input)
     -0:25.4.0 intentions:highlight (input.hidden-input)
     -0:24.6.0 core:save (input.hidden-input)
     -0:12.7.0 intentions:highlight (input.hidden-input)
     -0:12.1.0 jsdoc:block (input.hidden-input)
```

### Non-Core Packages

```
atom-easy-jsdoc 4.12.4 
auto-softwrap 1.0.1 
autocomplete 0.47.0 
autocomplete-glsl 0.2.3 
autocomplete-modules 1.10.0 
busy-signal 1.4.3 
chary-tree-view 0.2.13 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.6 
city-lights-ui 1.3.1 
hyperclick 0.1.5 
indentation-indicator 1.1.0 
intentions 1.1.5 
ir-black-k-syntax 0.2.3 
js-hyperclick 1.12.2 
language-json-comments 0.16.3 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.8.0 
space-tab 0.4.2 
sync-settings 0.8.3 
tree-view-autoresize 2.3.0 
zentabs 0.8.9 
```

**Comment by tgandrews** [comment]
Thanks that’s a great report. I’ll have a look this evening.
